### ISSUE TITLE
No results with simulate

### ISSUE THREAD

**Issue by zounp** [Taggic/langdelete#10]
Hello,

When file in one two letter code besides en and check
   simulate only
on I only get
   Results
   The following language directories will be deleted.

   Please take care that you select properly, which languages to be kept. There does not exist 
   an Undo function.
The languages are there, I checked
Any ideas?
Thanks

**Comment by Taggic** [comment]
Hi,

corection available. please downoad and update your plugin.

br
taggic

Am 04.07.2016 um 23:53 schrieb zounp:

**Comment by zounp** [comment]
Hi Taggic, Works, simulate and delete :-)Its a long list :-)Thanks for the pluginThanks and Regards,Zounp 08.07.2016, 18:32, "Taggic" <notifications@github.com>:Hi,  corection available. please downoad and update your plugin.  br taggic  Am 04.07.2016 um 23:53 schrieb zounp: > > Hello, > > When file in one two letter code besides en and check > simulate only > on I only get > Results > The following language directories will be deleted. > > Please take care that you select properly, which languages to be kept.  > There does not exist > an Undo function. > The languages are there, I checked > Any ideas? > Thanks > > — > You are receiving this because you are subscribed to this thread. > Reply to this email directly, view it on GitHub  > <https://github.com/Taggic/langdelete/issues/10>, or mute the thread  > <https://github.com/notifications/unsubscribe/AAnlcYTSQRoSBehOJokzMn-PW6IXe4pHks5qSYDWgaJpZM4JEqne>. > —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.   -- Regards,ZoUnp
