### ISSUE TITLE
All languages are listed for deletion

### ISSUE THREAD

**Issue by jFMd21** [Taggic/langdelete#14]
Hello Taggic,

when the latest version of your plugin is run on the latest version of Dokuwiki (this was actually also happening on Elenor of Trust) on Windows & IIS, I get the following result for a simulation:

![image](https://cloud.githubusercontent.com/assets/26376634/23849662/b5f7d942-07dc-11e7-9fb8-21dd4af544a8.png)

There will also be some languages not to keep in the list later on for some plugins, (e.g. D:\dokuwiki/lib/plugins/gallery/fr).

Note the Win-untypical notation of the path using "/" instead of "\". However this would also jump to the right folder used in a command prompt or Win Explorer.

Thx for help...

**Comment by Taggic** [comment]
corrected now, there was a change by somebody leading into trouble due to insufficent testing :-(

**Comment by jFMd21** [comment]
Thx Taggic, error corrected: correct languages to delete are listed, so far no further files deleted found...
:-)
