### ISSUE TITLE
2014-09-29b "Hrun" - 

### ISSUE THREAD

**Issue by LMS235** [Taggic/langdelete#3]
There are no languages listed for deletion even though some are installed

![langdel](https://cloud.githubusercontent.com/assets/8693550/5353880/d95fde58-7f7f-11e4-9e88-92f6cea260c8.png)

**Comment by wolfgangasdf** [comment]
Hi, just had the same, it is most likely that after an update (using tar etc), the webserver-user cannot delete the files anymore. I do a "chmod -R go+rw" on the lib and inc folders to resolve this.

But the real problem is that the langdelete plugin does not check (in admin.php) the return code of `php unlink` [[http://php.net/manual/en/function.unlink.php]]. Without this check, the message "-> file deleted" is only wishful thinking ;-)

**Comment by Taggic** [comment]
Please exchang the function *_rrmdir_ *by following code to get proper 
response:

     function rrmdir($dir) {
         // replace "//" in $dir if existing
         $dir = str_replace('//', '/', $dir);

         if (is_dir($dir)) {
             $objects = scandir($dir);
             foreach ($objects as $object) {
                 if ($object != '.' && $object != '..') {
                     if (filetype($dir.'/'.$object) == 'dir') {
                         $this->rrmdir($dir.'/'.$object);
                         echo '<strong>'.$dir.'/'.$object.' ->directory 
removed</strong><br />';
                     } else {
*                       $result = @unlink($dir.'/'.$object);**
**                       if($result === true) echo $dir.'/'.$object.' -> 
file deleted<br />';**
**                       else echo $dir.'/'.$object.'<span 
style="color:red;"><b> -> file not deleted</b></span><br />';*
                     }
                 }
             }
             reset($objects);
             @rmdir($dir);
         }
     }



Am 12.01.2015 um 18:49 schrieb wolfgangasdf:

**Comment by Taggic** [comment]
Further, insert the following code line before $result = ... will solve 
the pemission issue you reported.

chmod($dir.'/'.$object, 0755);

Both corrections will become part of the next release.

br
Taggic

Am 12.01.2015 um 18:49 schrieb wolfgangasdf:

**Comment by Taggic** [comment]
seems to be similar to the issue you resolved already by your own ?

**Comment by LMS235** [comment]
problem still exists

**Comment by Taggic** [comment]
please try again with new Version of langdelete plugin

**Comment by LMS235** [comment]
its ok now :)
