### ISSUE TITLE
No languages listed for delete if input 'de' when current language is 'de-informal'

### ISSUE THREAD

**Issue by thomaspahl** [Taggic/langdelete#5]
In #3, the input was given as `de, de-informal, en` - this will always cause trouble because the languages must be comma-separated **without** spaces.

My situation differs: up-to-date DW, plugin freshly installed. Current language is `de-informal`. As soon as I enter `de` in the list of languages to keep, the list of languages to be deleted is empty (dry run tested).
The list is also wrong if I enter any of  `hu,id,pt,zh` - which incorrectly keep `hu-formal,id-ni,pt-br,zh-tw`.

Cause is the incorrect logic around lines 148-155 in admin.php.
I changed lines 147-156 to the following (shorter) code:

``` php
    // are we processing a language directory?
    if ((substr($path, -5, 5) == '/lang') and !in_array($file, $lang_keep)) {
             $dir = "$path/$file";
```

resulting in a correct delete list so far.

**Comment by Taggic** [comment]
after the pdates I'm not really sure where you inserted this code. Could you please check it again ?

**Comment by Taggic** [comment]
new version available
